import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bird,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  CalendarDays,
  Camera,
  Check,
  ClipboardList,
  Coins,
  Construction,
  Crown,
  Gem,
  Globe2,
  GraduationCap,
  Hammer,
  Handshake,
  Heart,
  Home,
  House,
  Info,
  KeyRound,
  Landmark,
  Lightbulb,
  Library,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Mountain,
  TreePalm,
  PartyPopper,
  Settings,
  Phone,
  Rocket,
  Search,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Twitter,
  UserRound,
  Users,
  Video,
  Wrench,
  X,
  Zap,
  ShieldCheck,
} from 'lucide-react';

const ICON_MAP = {
  '🏔️': Mountain,
  '🏘️': Building2,
  '🏛️': Landmark,
  '🏠': Home,
  '🏡': House,
  '🏙️': Landmark,
  '🏢': Building,
  '🏗️': Construction,
  '🔍': Search,
  '⭐': Star,
  '👑': Crown,
  '🔑': KeyRound,
  '🌱': Sprout,
  '🤝': Handshake,
  '🎓': GraduationCap,
  '📈': TrendingUp,
  '📊': BarChart3,
  '✨': Sparkles,
  '💭': MessageCircle,
  '💬': MessageCircle,
  '🏆': Trophy,
  '💰': Coins,
  '🚀': Rocket,
  '⚡': Zap,
  '📅': CalendarDays,
  '📞': Phone,
  '📱': Smartphone,
  '⏱️': Timer,
  '→': ArrowRight,
  '←': ArrowLeft,
  '❤️': Heart,
  '🎯': Target,
  '📋': ClipboardList,
  '🔒': Lock,
  '🔨': Hammer,
  '🔧': Wrench,
  '📘': BookOpen,
  '🐦': Bird,
  '💼': BriefcaseBusiness,
  '📧': Mail,
  '📍': MapPin,
  '🚌': Bus,
  '👩‍💼': UserRound,
  '👥': Users,
  '💡': Lightbulb,
  '🗺️': Map,
  '🌐': Globe2,
  '🏝️': TreePalm,
  '⚙️': Settings,
  '🛡️': ShieldCheck,
  '⚠️': AlertTriangle,
  '✅': Check,
  '✓': Check,
  '✕': X,
  '🎉': PartyPopper,
  '📚': Library,
  'ℹ️': Info,
  '❗': AlertCircle,
  '📢': Megaphone,
  '📸': Camera,
  '💎': Gem,
  '🎥': Video,
  // ASCII-friendly aliases
  home: Home,
  house: House,
  building: Building,
  construction: Construction,
  neighborhood: Landmark,
  map: Map,
  'map-pin': MapPin,
  search: Search,
  phone: Phone,
  email: Mail,
  calendar: CalendarDays,
  checklist: ClipboardList,
  rocket: Rocket,
  sparkles: Sparkles,
  chat: MessageCircle,
  users: Users,
  user: UserRound,
  trophy: Trophy,
  money: Coins,
  analytics: BarChart3,
  growth: TrendingUp,
  star: Star,
  crown: Crown,
  key: KeyRound,
  handshake: Handshake,
  goal: Target,
  success: Check,
  warning: AlertTriangle,
  alert: AlertCircle,
  info: Info,
  idea: Lightbulb,
  books: Library,
  book: BookOpen,
  party: PartyPopper,
  lock: Lock,
  hammer: Hammer,
  bus: Bus,
  mobile: Smartphone,
  video: Video,
  camera: Camera,
  megaphone: Megaphone,
  gem: Gem,
  wrench: Wrench,
  palm: TreePalm,
  globe: Globe2,
  settings: Settings,
  arrow: ArrowRight,
  'arrow-right': ArrowRight,
  shield: ShieldCheck,
  back: ArrowLeft,
} as const satisfies Record<string, LucideIcon>;

export type IconSymbolKey = keyof typeof ICON_MAP;

interface IconSymbolProps {
  symbol: IconSymbolKey;
  className?: string;
  size?: number;
  strokeWidth?: number;
  ariaLabel?: string;
}

export function IconSymbol({
  symbol,
  className,
  size = 24,
  strokeWidth = 2,
  ariaLabel,
}: IconSymbolProps) {
  const IconComponent = ICON_MAP[symbol];

  if (!IconComponent) {
    return (
      <span className={className} role="img" aria-label={ariaLabel}>
        {symbol}
      </span>
    );
  }

  const mergedClassName = ['shrink-0', className].filter(Boolean).join(' ');

  return (
    <IconComponent
      className={mergedClassName}
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden={ariaLabel ? undefined : true}
      aria-label={ariaLabel}
    />
  );
}
